version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  client:
    build: ./client
    container_name: client
    stdin_open: true
    tty: true
    depends_on:
      - redis

  suscriptor:
    build: ./processor
    container_name: processor
    depends_on:
      - redis

